# Generated by Django 2.2.7 on 2019-11-06 06:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20190824_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=django.contrib.auth.models.User, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
